### ISSUE TITLE
Unable to install node-sass with node v0.10.x

### ISSUE THREAD

**Issue by BOHverkill** [Athou/commafeed#747] opened 2015-07-25 11:47 UTC
In node version 0.10.x is a bug so that the libsass binding is stored at the wrong location, so i am unable to build commafeed.

Could you please update the pom.xml so it is using node>=v0.12.0

See: https://github.com/sass/node-sass/issues/969

thx!

**Comment by Athou** [comment] 2015-07-25 12:17
What OS are you trying to build on? It works fine here on windows and linux.

**Comment by BOHverkill** [comment] 2015-07-25 12:19
On Arch Linux 64bit

**Comment by Athou** [comment] 2015-07-25 12:19
Could you try to delete the `node` and `node_modules` directories and restart the build?

**Comment by BOHverkill** [comment] 2015-07-25 12:30
I tried that several times, I also recloned the repo. 
Always the same error

**Comment by Athou** [comment] 2015-07-25 15:10
Since I can't reproduce the issue, I'm going to need your help.
Could you try to change the node version in pom.xml until you're able to find a working version?

**Comment by Athou** [comment] 2015-07-25 15:36
Okay I think I understand, it seems that node-sass is using the globally-installed version of node during its build if there's one, but gulp-sass is using the one dowloaded by maven.

I can reproduce the issue by installing node 0.12 on my linux box.

Let me see if I can fix the issue.

**Comment by Athou** [comment] 2015-08-10 17:25
It should be fixed when the new version of frontend-maven-plugin is released

**Comment by Athou** [comment] 2015-08-22 11:50
This issue should be fixed now!

**Closed** 2015-08-27 07:58 UTC

**Comment by BOHverkill** [comment] 2015-09-05 19:10
Thx for fixing :smile: :+1:
