### ISSUE TITLE
Basic Http Auth being stripped from url field.

### ISSUE THREAD

**Issue by gomyar** [Athou/commafeed#784] opened 2016-02-24 23:36 UTC
When subscribing to a feed url which contains http auth : http://username:password@feed.com

The name of the feed is first retrieved successfully, but when saving the feed, the username:password is stripped from the url, and the save fails.

Presumably this is something to do with how the http url is parsed. Basic Auth does not appear to survive the parsing the second time (but works on the initial feed details, i.e. feed name).

It's difficult to give an example without posting up private credentials to the ticket, so apologies about that, but the reproduction steps are:

1. Go to "Subscribe"
2. Enter a feed url which requires basic http auth.
2a. The feed name is populated correctly, but you can see the url now no longer contains the username/password
3. Click "Save"
3a. The form hangs attempting to connect to the feed.

**Comment by Athou** [comment] 2016-02-25 05:49
duplicate of https://github.com/Athou/commafeed/issues/775

**Closed by Athou** 2016-02-25 05:49 UTC
